# Start with a base image
FROM golang:1.22.2

# Set the working directory inside the container
WORKDIR /usr/src/app

COPY go.mod go.sum ./

RUN go mod download && go mod verify 


# Copy the source code into the container
COPY . .

# Compile the Go application
RUN go build -o /usr/local/bin/app .

# Expose the port that the application will run on
EXPOSE 8080

# Run the application
CMD ["/usr/local/bin/app"]
